#kubectl create secret generic db-creds --from-literal=dbuser=admin --from-literal=dbpass=123456

apiVersion: v1
kind: Pod
metadata:
  name: secret1
spec:
  containers:
    - image: nginx
      name: container1
      envFrom:
        - secretRef:
            name: db-creds
